name: devpi-docker

services:
  devpi-server:
    build: .
    container_name: devpi-server
    ports:
      - ${MAPPED_PORT}:${DEVPISERVER_PORT}
    environment:
      - DEVPI_OUTSIDE_URL=${DEVPI_OUTSIDE_URL}
      - DEVPISERVER_HOST=${DEVPISERVER_HOST}
      - DEVPISERVER_PORT=${DEVPISERVER_PORT}
      - DEVPISERVER_SERVERDIR=${DEVPISERVER_SERVERDIR}
      - DEVPI_ROOT_PASSWORD=${DEVPI_ROOT_PASSWORD}
      - DEVPI_USER=${DEVPI_USER}
      - DEVPI_USER_PASSWORD=${DEVPI_USER_PASSWORD}
    volumes:
      - ${DATA_VOLUME}:/data/devpi
    restart: unless-stopped
